CircleCI-Public/orb-tools-orb

- .circleci/config.yml
Looks like Error message from orb validate changed from:
> There is an error in the config file
to
> Error: ERROR IN CONFIG FILE:
Not sure if we intended that, so adding @ndintenfass  to this PR.
> update invalid config message to match latest from cli

- LICENSE
- src/jobs/trigger-integration-workflow.yml
currently, the automated `git diff`-parsing logic in the `trigger-integration-workflow` job sets up the possibility of a major release anytime there are _any_ modifications whatsoever to `src/jobs` or `src/commands`. this is probably too low of a bar—major releases should represent some actual significant change to an orb.
expand our `git diff` logic just a bit. only set up a major release if there are _new_ jobs or commands. otherwise, modifications to existing jobs or commands trigger a  possible minor release. everything else that affects orb source code triggers a possible patch release. completely skip publishing if no actual orb source has been altered.
also, add MIT license, addressing https://github.com/CircleCI-Public/orb-tools-orb/issues/4
> more strict gating on major releases

- .circleci/config.yml
- publish-alpha.sh
- src/jobs/trigger-integration-workflow.yml
the tag-triggered integration testing workflow results in creation of lots of tags, which by default are orphaned unless someone specifically adds logic to clean them up
add param to the `trigger-integration-workflow` job to clean up old tags before pushing a new one
> add cleanup-tags option

- README.md
The status badge currently doesn't link to CircleCI builds of the project.
Make the status badge link to the CircleCI builds of the project
> Fix status badge link

- src/jobs/trigger-integration-workflow.yml
- [ - ] All new jobs, commands, executors, parameters have descriptions
- [ - ] Examples have been added for any significant new features
- [ - ] README has been updated, if necessary
Currently while working on another orb I am running into issues with my tags not appearing within the container. It appears the tag cleanup step of this orb may be too aggressive and removing all tags, not just the ones created be this orb.
This change should limit tag deletion to only tags beginning with "integration-*" as to leave any other tags unaffected. (It may be a good idea to come up with a more unique tag identifier in the future).
> This should limit tag deletion to only integration based tags.

- src/jobs/trigger-integration-workflow.yml
In specific cases, it is not necessary to use the `add_ssh_keys`
command prior to pushing the tag.
Make the specification of the `ssh-fingerprints` parameter optional
and only execute the `add_ssh_keys` step if fingerprints are provided.
Addresses: #23
> jobs/trigger-integration-workflow: Make ssh-fingerprints optional

- .circleci/config.yml
- src/executors/alpine.yml
- src/executors/ci-base.yml
- src/executors/lint.yml
- src/executors/machine.yml
- src/executors/macos.yml
- src/executors/node-cci.yml
- src/executors/node.yml
- src/executors/ubuntu.yml
- src/jobs/trigger-integration-workflow.yml
a lot of orbs end up using the same executors to test orb functionality across various execution environments. by hardcoding them into orb-tools, we can save a lot of boilerplate in orb repos' config.yml files
add executors commonly used in orb-testing
> Add common testing executors

- src/jobs/trigger-integration-workflow.yml
In my use case I have a mono-repository for all my orbs. I need to be able to specify the tag used during the job `trigger-integration-workflow` to be able to trigger different deployment according to which orbs have been changed.
- modify `tag` parameter to job `trigger-integration-workflow` from `enum` to `string`
> fix: Allows to use any string as tag for trigger-integration-workflow

- .circleci/config.yml
- src/commands/check-env-var-param.yml
- `check-env-var-param` currently can only check 1 parameter, which is a slightly blocking limitation to widespread usage
- make it take a comma-separated list of strings, check each
> `check-env-var-param` can check multiple env var params

- src/jobs/dev-promote-prod.yml
`dev-promote-prod` can now publish SemVer tag releases, which is awesome, but they're fairly minimal
flesh out the version tag that gets created, by adding a tag message body including a link to the registry URL for that specific release (don't merge this until AFTER that registry functionality is in production) & the circleci CLI command to view that SemVer in your terminal
> [WIP] populate git tag message

- src/jobs/trigger-integration-workflow.yml
resolves #41 
Change `trigger-integration-workflow` to make its `cleanup-tags` option delete previous tags matching the `tag` parameter.
> trigger-integration-workflow: make cleanup-tags use tag parameter

- src/jobs/dev-promote-prod.yml
- src/jobs/trigger-integration-workflow.yml
We've made some changes to the tag deletion recently, and I wanted to make things a bit better, if possible.
Rather than hardcoding certain tagging patterns for optional deletion, just fully parameterize the `git tag -l` pattern that will be cleaned up.
Also, add the same functionality to the `dev-promote-prod` job, since it was already doing some (previously hardcoded) optional tag cleanup.
The goal here is to have orb repos where the only tags that remain, are those following a `vX.Y.Z` SemVer pattern, which is the default published when using `dev-promote-prod` with `publish-version-tag` set to `true`.
The way to achieve this is specified in the default values for `cleanup-tags-pattern` in both jobs in which it now appears:
- In `trigger-integration-workflow`, the default will cleanup …
> Revise tag cleanup

- src/jobs/lint.yml
Signed-off-by: Andrew Suderman <andrew@sudermanjr.com>
Fixes #45 
When building an annotated tag, git and openssh are required to checkout.
Add a run block before code checkout that runs `apk --update add git openssh`
> Installing git and openssh when checkout is specified

- src/commands/configure-git.yml
- src/jobs/dev-promote-prod.yml
- src/jobs/trigger-integration-workflow.yml
Follow-up from https://github.com/CircleCI-Public/orb-tools-orb/issues/61
Extracting a command for setting git config and enabling custom git config, with fallback to todays values. Backwards compatible.
I checked the "examples and README" part of the checklist as this is a minor change. But as I propose in my issue #61 this might also be added as parameters to the jobs that use it, and then it would also show up as an option on the orb registry page.
I'll make appropriate changes to the PR if needed.
> Add possibility for custom git user name/email config #61

- src/jobs/dev-promote-prod.yml
None.
I believe the unused parameter should be removed. :)
> Remove unused parameter `cleanup-tags` in dev-promote-prod job

- .circleci/config.yml
- README.md
- src/commands/dev-promote-semver.yml
- src/examples/orb-dev-workflows.yml
- src/jobs/dev-promote-prod.yml
This would be a [semver:major] change I think.
Rather than hard-coding the major,minor, patch increment, it will be
deciphered by the commit message, expecting the form `[semver:FOO]` in the subject.
This is major change because users will get a failure message if they do
not include that in the commit to a branch using the dev-promote job or command.
Optionally the prod version can be published by a bot back to GitHub PR. This is included because it uses the output of the promote command, but could be refactored into its own command.
> Adds opinionated semver promote command and use in promote job [semver:major]

- src/commands/check-env-var-param.yml
The `check-env-var-param` command was not working as expected.
In order to evaluate whether a string is defined as a variable, you'll need to use an indirect shell [parameter expansion](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html):
> The basic form of parameter expansion is ${parameter}. The value of parameter is substituted.
>
> If the first character of parameter is an exclamation point (!), it introduces a level of variable indirection. Bash uses the value of the variable formed from the rest of parameter as the name of the variable; this variable is then expanded and that value is used in the rest of the substitution, rather than the value of parameter itself.
> Fix parameter expansion on check-env-var-param command

- .circleci/config.yml
- src/commands/dev-promote-from-commit-subject.yml
- src/jobs/dev-promote-prod-from-commit-subject.yml
This PR resolves https://github.com/CircleCI-Public/orb-tools-orb/issues/76 . Even when `publish-tag` is set to `true` , tag publishing should be skipped when the semver increment is `skip` or not indicated. Additionally, the orb version number used for tag publishing is now obtained in a more accurate manner.
There are also other changes in the PR, which don't affect orb behavior:
- Update version of `orb-tools` orb used in build
- Fix the build; it is now using a newer version of the `circleci-cli` orb which requires `jq` to be installed, causing the `test-commands-node` job to fail as that image doesn't come with `jq`.
- Fix the  "test-promote-from-git-tag" integration test (see [CIRCLE-23282])
[CIRCLE-23282]: https://circleci.atlassian.net/browse/CIRCLE-23282
> Always skip tag publishing when semver increment is "skip" or not indicated [semver:patch]

- src/commands/dev-promote-from-commit-subject.yml
- src/commands/dev-promote-from-git-tag.yml
- src/commands/increment.yml
- src/commands/local-test-build.yml
- src/commands/pack.yml
- src/commands/publish.yml
- src/commands/validate.yml
This avoids calling the GitHub Releases API to do a check for updates, and helps avoid rate limiting.
> Add --skip-update-check flag to the circleci cli commands [semver:patch]

- src/commands/dev-promote-from-git-tag.yml
The token-variable is provided as a parameter but not used. Use the provided one, or the defined default if not
The parameter provided to the command was not being used. As a result it was not possible to change the environment variable that the token should be read from. 
add the usage of the `token-variable` parameter to the generated command
> [semver:patch] Use the provided token-variable parameter

- src/commands/install-bats.yml
A more detailed error message and extended error checking instead of blindly falling back to a second approach
* Replace the blind fallback to trying without sudo with a more complete check whether it is required to use sudo.
* Throw an error if required permissions to run `install.sh` are not available.
* validate bats installation by executing it
> [semver:minor] Use permissions checks for bats install

- src/commands/pack.yml
This will let users use "include" in their syntax
Adds an option to use the be orb pack command instead of the config pack command
> [semver:minor] Add orb pack option

- src/jobs/pack.yml
Ensure `use-orb-pack` can be passed through the job.
> [semver:patch] Add use-orb-pack to pack job.

- src/examples/full.yml
- src/examples/orb-dev-workflows-git-tag.yml
- src/examples/orb-dev-workflows.yml
This fixes #99 and removes references to the (now outdated) job `orb-tools/shellcheck` since it has moved into its own orb.
> [semver:patch] Remove references to outdated job

- src/scripts/post-pr-comment.sh
as this is how it is defined in https://github.com/CircleCI-Public/orb-tools-orb/blob/master/src/commands/post-pr-comment.yml
- ~~All new jobs, commands, executors, parameters have descriptions~~
- ~~Examples have been added for any significant new features~~
- ~~README has been updated, if necessary~~
When enabling the Github comment (see the `add-pr-comment` parameter in [dev-promote-from-commit-subject](https://circleci.com/developer/orbs/orb/circleci/orb-tools#commands-dev-promote-from-commit-subject)), the command saves the parameter as the `BOT_TOKEN` environment variable, the script however uses the `TOKEN` variable. This makes it impossible to use the `add-pr-comment: true` setting.
use BOT_TOKEN instead of TOKEN in post-pr-comment.sh
> [semver:patch] use BOT_TOKEN instead of TOKEN

- src/examples/orb-dev-workflows-git-tag.yml
- src/examples/orb-dev-workflows.yml
When I read [this page](https://circleci.com/developer/orbs/orb/circleci/orb-tools) I noticed that the correct job names are different from the description.
> [semver:patch] Fix job name in description

- src/scripts/dev-promote-from-commit-subject.sh
- [n/a] All new jobs, commands, executors, parameters have descriptions
- [n/a] Examples have been added for any significant new features
- [n/a] README has been updated, if necessary
In the [`dev-promote-from-commit-subject` command's definition](https://circleci.com/developer/orbs/orb/circleci/orb-tools?version=10.0.3#commands-dev-promote-from-commit-subject), the function `CheckIncrement` relies on a conditional expression to decide whether or no to fail the build if the commit subject doesn't include a `SemVer` increment:
```
if [ "$SHOULD_FAIL" == "true" ];then
exit 1
```
`SHOULD_FAIL` is defined as an environment variable of the related step:
`SHOULD_FAIL: <<parameters.fail-if-semver-not-indicated>>`
However, as the shell environment variable `SHOULD_FAIL` will only ever resolves as …
> [semver:patch] Ensure `fail-if-semver-not-indicated` parameter set to `true` is honored

- src/commands/post-pr-comment.yml
- src/scripts/post-pr-comment.sh
The variable handling for `BOT_TOKEN` was broken in the `post-pr-comment` command, when using this with `dev-promote-from-commit-subject` and parameter `add-pr-comment: true`, the step `Post comment to GitHub pull request` would show a failed curl api call:
```
{
"message": "Not Found",
"documentation_url": "https://docs.github.com/rest/reference/issues#create-an-issue-comment"
}
```
Traced this to the `BOT_TOKEN` environment variable not being dereferenced properly.
Removed the extraneous `$` prefix on the environment value; and added a bash dereference modifier (`${!`) to the script, tested (it works).  Not sure what the point of the interim `BOT_TOKEN` environment variable was at all, instead of simply passing the `<< parameter.bot-token-variable >>` right into the curl call, but I …
> [semver:patch] Fix improperly dereferenced variable for GitHub

- .circleci/config.yml
- .circleci/test-deploy.yml
- src/examples/step1_lint-pack.yml
- src/examples/step2_test-deploy.yml
- src/jobs/publish.yml
- src/scripts/comment-pr.sh
- src/scripts/publish.sh
Ran into an issue when publish orb tools 11, the tag was present so the prod version was published immediately before the tests. This new dev parameter allows the first publish job to _only_ publish dev tags.
> feat: Changes parameters to fix production publishing

- src/scripts/review.bats
Ex: Nodejs `https://nodejs.org/` redirects to `https://nodejs.org/en/`, and does not initially respond with a 200 response. This might not be the best solution for all URL responses that could be considered valid.
> fix: Follow home_url redirects for bats review

- src/scripts/review.bats
This should have been fixed with RC007 but the `-L` flag was only applied to one.
We might have thought that there may be no need to detect a redirect from GitHub, however, it looks like even a _brand new_ repo thats never had a modified URL can return a 301. I just created a repo and I see GitHub appears to be returning a 301, then going back to the exact same URL, but with HTTP2 enabled.
```
> Host: www.github.com
> user-agent: curl/7.79.1
> accept: */*
> 
< HTTP/2 301 
< content-length: 0
< location: https://github.com/KyleTryon/calculator-orb
< 
{ [0 bytes data]
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host www.github.com left intact
* Issue another request to this URL: 'https://github.com/KyleTryon/calculator-orb'
*   Trying …
```
> fix: missing redirect for RC006

- src/scripts/review.bats
Fixes a minor typo in the bats review output when the orb-tools identifies a long line not imported.
> fix(review): Fix typo in review script

- src/scripts/continue.sh
I referred below link to set correct repo name.
https://circleci.com/docs2/2.0/env-vars#built-in-environment-variables
> fix: correct URL to view pipeline after publish

- src/executors/default.yml
- src/jobs/continue.yml
- src/jobs/lint.yml
- src/jobs/pack.yml
- src/jobs/publish.yml
- src/jobs/review.yml
- Add the ability to set resource classes for jobs, setting the default `resource_class` to `medium`.
- Add a new `default` executor here; replacing the one we called from CircleCI-Public/circleci-cli-orb
- Update cimg python executor to `cimg/python:3.10.5`
See also
CircleCI-Public/circleci-cli-orb#17
> feat(jobs): add `resource_class` overrides

- src/jobs/review.yml
- src/scripts/review.bats
Closes #151 
This PR adds a new parameter to allow the customization of the maximum allowed character length in commands.
> feat: parameterize the command's maximum allowed length (RC009)

- src/jobs/review.yml
- src/scripts/review.bats
The parameter included in #169 didn't use the YAML's correct argument. Additionally, the error message had a hard-coded character count.
Fix the YAML's parameter and the error message.
> fix: parameter sent to `review.bats`

- src/executors/default.yml
- src/jobs/continue.yml
- src/jobs/pack.yml
- src/jobs/publish.yml
- src/jobs/review.yml
This feature is modeled after https://github.com/CircleCI-Public/shellcheck-orb/blob/master/src/jobs/check.yml#L7 .
I'm attempting to author an Orb within my company's CircleCI Server v3 instance.  We have imported the orbs published under the `circleci/*` namespace. When using the jobs defined in this Orb, I'm getting the following error message at the `checkout` step:
```
Using SSH Config Dir '/home/circleci/.ssh'
git version 2.38.0
Cloning git repository
Cloning into '.'...
error: cannot create async thread: Operation not permitted
fatal: fetch-pack: unable to fork off sideband demultiplexer
exit status 128
CircleCI received exit code 128
```
I'd like this feature as a work-around to the potential underlying issue described [here](https://bugs.launchpad.net/ubuntu/+bug/1992485). The …
> feat: allow consumer to set tag for CircleCI images

- src/jobs/review.yml
It has been discovered that the RC008 review job does not work with versions of YQ v4.29.1 or higher. Pinning the review job tag to the last known good tag for cimg/base which contains YQ version `4.27.5`.
> fix: set known good image tag to fix yq

- src/scripts/publish.sh
I know the resolution of this issue can appears weird. But it just happen to me and I had to look at the source code to understand. 
Also I think the doc should mention that it is required.
This is ORB_PARAM_ORB_PUB_TOKEN but it is defined via a parameter with a default as CIRCLE_TOKEN.
If you set ORB_PARAM_ORB_PUB_TOKEN in a context it will not work with the orb template but if you set CIRCLE_TOKEN it is working properly.
> Prevent invalid warning when var ENV 'ORB_PARAM_ORB_PUB_TOKEN' isn't define

- src/jobs/publish.yml
- src/scripts/publish.sh
> feat: custom publishing tag pattern

- src/jobs/publish.yml
- src/scripts/publish.sh
Fix for #182 - Make orb release version greedy for patch versions
> fix: Make orb release version regex greedy for patch versions

- src/jobs/review.yml
Signed-off-by: Adam Harvey <adaharve@cisco.com>
This PR fixes a trivial typo of a double quote in a description, but attempts to also slightly improve the wording when it refers to review checks.  (early on, I kept forgetting what "RC" stood for)
> chore: Improve wording relating to review checks

- .circleci/config.yml
We originally thought these filters may not be needed, however, when we attempted to publish, the workflow did not trigger. Adding back these filters.
> fix: add tag filters

- src/executors/default.yml
Update the cli docker image to include newest updates for private orb support
> chore: update CLI

- src/scripts/review.sh
Use pretty output to stdout / stderr, and then also save the junit report
The test results will still be included in the "tests" tab, but this should make the test output a little easier to follow.
note: I'm happy to add back the additional messages and exit code / pointer to look at the tests, but I think this may work as expected without it?
> feat(scripts): add pretty output to review job

- src/scripts/review.bats
> fix: RC010 should ignore components without parameters

- src/scripts/continue.sh
This change leverages the [load function](https://mikefarah.gitbook.io/yq/operators/load#replace-node-with-referenced-file) from yq.
It allows us to load the full content from a YAML file. This way, we do not need to cat the YAML file content in a prior step.
In addition, I believe this can avoid the 'Argument list too long' yq error.
Related: https://stackoverflow.com/questions/70278587/yq-v4-env-operator-returning-errnoe2big-argument-list-too-long
I've made [a sample project](https://github.com/kelvintaywl-cci/explore-yq) to showcase the proposed change.
Public workflow here:
https://app.circleci.com/pipelines/github/kelvintaywl-cci/explore-yq/2/workflows/12f05943-7c50-453b-a680-210979221316/jobs/2
I confirmed that the executors have yq >= 4.x so the load function should indeed be …
> fix: use load to slurp YAML file

- src/examples/step2_test-deploy.yml
One of the examples uses pre-v12 property names which would fail the command run.
> fix: update outdated property names in step2_test-deploy.yml

- .circleci/config.yml
- .circleci/test-deploy.yml
- src/examples/step1_lint-pack.yml
- src/jobs/review.yml
- src/scripts/review.bats
This new review job ensures you do not publish a major version change prior to updating the usage examples of the orb. This is only scoped to the major version, some users I imagine will want even more strict checks in place, I think we may want to address that with an additional test that could independently be enabled or disabled. Depending on feedback, I will leave that for a future change.
> feat: new RC011 testing for usage example updates

- src/jobs/publish.yml
- src/scripts/publish.sh
The changes below add support for CircleCI's Releases. This addition adds an optional parameter to the publish job called `release_environment`. If `release_environment` is set, upon releasing a new version of the orb the release itself will be tracked in the supplied environment. 
Note users will need to make a custom environment type in CircleCI Releases and then pass that environment name as the parameter. 
By default `release_environment` is set to an empty string, which will skip over the release tracking. This should not break any usage of the existing orb tools.
> Enables Support for tracking Orb Releaes in CircleCI Releases

- .circleci/config.yml
- src/@orb.yml
- src/scripts/review.bats
- src/scripts/review.sh
v11.1.0 + including v12
First described in #128 by @wyardley, run-steps within conditional steps are not checked by RC008 and RC009
This is expected to fail RC008 and RC009
```yaml
steps:
- checkout
- restore-deps
- run: npm run thing1
- when:
condition: << parameters.run-thing2 >>
steps:
run: npm run thing2
```
This PR fixes issue #132
> feat: conditional steps are now reviewed by RC008, RC009

- src/scripts/review.bats
This PR is meant to prevent errors like [this](https://github.com/CircleCI-Public/go-orb/pull/96) from happening again.
Tackles issue #246 .
1. identify which parameters are defined as Environment Variables
2. search where those parameters are being used directly inside key entries in the yml files
3. show the user information about incorrect usage of those parameters
Using a yml like the following:
```yml
description: "Save Go modules to cache."
parameters:
key:
description: "User-configurable component for cache key. Useful for avoiding collisions in complex workflows."
type: string
default: ""
path:
description: "Path to cache."
type: string
default: "/home/circleci/go/pkg/mod"
project-path:
description: |
The path to the directory containing your Go project files: go.mod, go.sum. …
```
> Adds new RC012 that checks how environment variables passed as parameters are being used

- src/executors/default.yml
there's a breaking change with old versions of the CircleCI CLI, it's probably best to just keep this on the latest image?
https://discuss.circleci.com/t/upcoming-breaking-change-to-circleci-local-cli-may-31-2025/52576
> update the default to use latest circlecicli image
