CircleCI-Public/orb-tools-orb

- .circleci/config.yml
- .github/ISSUE_TEMPLATE.md
- src/@orb.yml
- src/commands/extract-inline-orb.yml
- src/executors/ci-base.yml
- src/executors/lint.yml
- src/jobs/dev-promote-prod.yml
- src/jobs/lint.yml
- src/jobs/publish-dev.yml
- src/jobs/publish.yml
- src/jobs/trigger-integration-workflow.yml
finally abstracting out a bunch of my [default orb-testing jobs](https://discuss.circleci.com/t/emerging-testing-best-practices-for-orbs) into this orb
> [WIP] Add orb testing

- .circleci/config.yml
- src/jobs/publish-dev.yml
- src/jobs/trigger-integration-workflow.yml
use new orb tools jobs in orb tools config
also fix some of the new jobs in the process
> Refactor config dogfood

- README.md
- src/@orb.yml
- src/examples/orb-dev-workflows.yml
not clear how to combine all the orb testing jobs
add full usage example combining all orb testing jobs into multiple workflows
> add full orb development workflows example

- .circleci/config.yml
- src/@orb.yml
- src/jobs/dev-promote-prod.yml
improve developer flow between github, circleci, & the registry
output link to orb in orb registry after publishing new prod release
> output link to registry after publishing new prod release

- src/commands/check-env-var-param.yml
(no significant new features, just a utility function, so no example nor README update)
The idea for this new command was suggested by @iynere during the discussion in this thread: https://discuss.circleci.com/t/new-orb-leanpub/29833/6
Added utility command to verify that an env-var parameter is defined, producing
an error otherwise, with an optional custom error message.
> New command check-env-var-param

- .circleci/config.yml
- src/@orb.yml
- src/jobs/trigger-integration-workflow.yml
config is less DRY than it could be
- remove some extra config
- bump some orb versions
- use new `compare-url/use` command
> use new compare-url command

- src/executors/oracle.yml
we want to be able to easily test a couple of orb commands on oracle linux
add an oracle linux executor
> add oracle linux executor for easier orb testing

- .circleci/config.yml
- src/jobs/trigger-integration-workflow.yml
https://github.com/CircleCI-Public/orb-tools-orb/pull/37
- allow any string to be passed as tag for integration workflow job
> Integration tag as string

- .github/ISSUE_TEMPLATES/bug_report.md
- .github/ISSUE_TEMPLATES/feature_request.md
The repository currently contains old version of issue template.
> Add issue templates

- src/@orb.yml
- src/commands/configure-git.yml
- src/jobs/dev-promote-prod.yml
- src/jobs/trigger-integration-workflow.yml
https://github.com/CircleCI-Public/orb-tools-orb/pull/62
> Add possibility for custom git user name/email config => master

- .circleci/config.yml
> Dummy non-master branch PR #2 for testing new semver release command

- .circleci/config.yml
Use latest dev orb, which supports skipping
> Dummy non-master branch PR #3 for testing new semver release command

- .circleci/config.yml
> Dummy non-master branch PR #5 for testing new semver release command 

- .circleci/config.yml
> Dummy non-master branch PR #6 for testing new semver release command

- .circleci/config.yml
> Dummy non-master branch PR #7 for testing new semver release command

- .circleci/config.yml
Test latest version of dev orb
> Dummy non-master branch PR #8 for testing new semver release command 

- .circleci/config.yml
- README.md
- publish-alpha.sh
- src/@orb.yml
- src/examples/orb-dev-workflows-git-tag.yml
- src/examples/orb-dev-workflows.yml
- src/jobs/shellcheck.yml
- tests/readme.md
- tests/shellcheck/commands/myCommand.yml
- tests/shellcheck/jobs/myJob.yml
Reverts CircleCI-Public/orb-tools-orb#81
> Reapply Shellcheck update [semver:minor]

- src/commands/trigger-integration-tests-workflow.yml
Adds a missing } when printing the integration job link.
> [semver:patch] Add missing }.

- src/commands/trigger-integration-tests-workflow.yml
- src/jobs/trigger-integration-tests-workflow.yml
- src/scripts/dev-promote-from-commit-subject.sh
- src/scripts/dev-promote-from-git-tag.sh
- src/scripts/trigger-integration-tests-workflow.sh
Just here to show progress more easily.
https://app.circleci.com/pipelines/github/CircleCI-Public/orb-tools-orb/641/workflows/0543af50-5943-4b56-b223-6c7f50736ba0/jobs/3875
This almost works.
> Orb pack 10 pipeline param

- .circleci/config.yml
- src/scripts/default-yamllint.sh
Update to new selected workflow names.
> Pack 10 workflow rename

- src/examples/step1_lint-pack.yml
Fix example steps
bad syntax 
**Closes Issues:**
- ISSUE URL
> chore(examples): remove extra `-` for steps

- migrate.sh
Remove invalid flag in the migration script.
> fix: invalid `git mv` flag in `migrate.sh`

- src/scripts/comment-pr.sh
Ensures to check the CircleCI PR variable is set before fetching PR data.
Closes #186
> fix: add check for PR existence before comment

- src/examples/step2_test-deploy.yml
> Update test deploy example with orb-tools/pack
